CREATE DATABASE USERS

USE USERS

CREATE TABLE LOGIN(
	ID CHAR(10) NOT NULL PRIMARY KEY,
	USERNAME VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(30) NOT NULL
);

INSERT INTO LOGIN VALUES ('1','admin','admin1');
INSERT INTO LOGIN VALUES ('4','a','a');